# Generated by Django 5.2.11 on 2026-02-05 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GmailConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('is_connected', models.BooleanField(default=False)),
                ('oauth_state', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gmail Connection',
                'verbose_name_plural': 'Gmail Connections',
            },
        ),
    ]
