# Generated by Django 5.2.10 on 2026-02-02 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0002_workspace_agent_description_workspace_agent_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('tool_type', models.CharField(choices=[('web_search', 'Web Search'), ('web_scrape', 'Web Scraper'), ('api_call', 'API Call'), ('file_read', 'File Reader'), ('send_message', 'Send Message'), ('code_execute', 'Code Executor')], max_length=50)),
                ('config_schema', models.JSONField(default=dict, help_text='JSON Schema for tool configuration')),
                ('is_global', models.BooleanField(default=True)),
                ('implementation', models.JSONField(default=dict, help_text='Implementation details (endpoint, code, etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('instructions', models.TextField(help_text='Natural language instructions for what the agent should do')),
                ('enabled_tools', models.JSONField(default=list, help_text='List of tool IDs the agent can use')),
                ('schedule', models.CharField(choices=[('once', 'Run Once'), ('hourly', 'Every Hour'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='once', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused')], default='pending', max_length=20)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('run_count', models.IntegerField(default=0)),
                ('last_result', models.TextField(blank=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_tasks', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('agent_reasoning', models.TextField(blank=True)),
                ('tools_used', models.JSONField(default=list)),
                ('steps_taken', models.JSONField(default=list)),
                ('result', models.TextField(blank=True)),
                ('result_data', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('tokens_used', models.IntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='automations.agenttask')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('data', models.JSONField(default=dict)),
                ('url', models.URLField(blank=True, max_length=2000)),
                ('score', models.FloatField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('is_new', models.BooleanField(default=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('is_saved', models.BooleanField(default=False)),
                ('user_rating', models.IntegerField(blank=True, null=True)),
                ('user_notes', models.TextField(blank=True)),
                ('found_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='automations.agenttask')),
                ('run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='structured_results', to='automations.taskrun')),
            ],
            options={
                'ordering': ['-score', '-found_at'],
            },
        ),
    ]
