# Generated by Django 5.2.10 on 2026-02-02 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('author_url', models.URLField(blank=True)),
                ('repository_url', models.URLField(blank=True)),
                ('icon_url', models.URLField(blank=True)),
                ('category', models.CharField(choices=[('productivity', 'Productivity'), ('development', 'Development'), ('data', 'Data & Analytics'), ('communication', 'Communication'), ('automation', 'Automation'), ('fun', 'Fun & Entertainment'), ('other', 'Other')], default='other', max_length=20)),
                ('tags', models.JSONField(default=list)),
                ('clawhub_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('version', models.CharField(default='1.0.0', max_length=50)),
                ('install_count', models.IntegerField(default=0)),
                ('is_official', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('skill_content', models.TextField(blank=True, help_text='SKILL.md content for this skill')),
                ('required_tools', models.JSONField(default=list, help_text='List of tools this skill requires')),
                ('required_env', models.JSONField(default=list, help_text='Environment variables required')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['-is_featured', '-install_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SkillRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('review', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='skills.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('skill', 'user')},
            },
        ),
    ]
