# Generated by Django 5.2.11 on 2026-02-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_add_job_search_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='version',
            field=models.CharField(default='1.0.0', max_length=100),
        ),
    ]
