# Generated by Django 5.2.10 on 2026-02-02 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('selected_model', models.CharField(choices=[('claude-opus-4-20250514', 'Claude Opus 4'), ('claude-sonnet-4-20250514', 'Claude Sonnet 4'), ('claude-3-5-haiku-20241022', 'Claude 3.5 Haiku'), ('gpt-4-turbo-preview', 'GPT-4 Turbo'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo')], default='claude-sonnet-4-20250514', max_length=100)),
                ('assigned_port', models.IntegerField(blank=True, null=True, unique=True)),
                ('container_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('deploying', 'Deploying'), ('running', 'Running'), ('stopped', 'Stopped'), ('error', 'Error')], default='pending', max_length=20)),
                ('last_health_check', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('sandbox_mode', models.BooleanField(default=True, help_text='Enable sandbox mode for safe execution')),
                ('max_tokens', models.IntegerField(default=4096)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workspace',
                'verbose_name_plural': 'Workspaces',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstalledSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(default=dict, help_text='Skill-specific configuration overrides')),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='skills.skill')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installed_skills', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Installed Skill',
                'verbose_name_plural': 'Installed Skills',
                'ordering': ['-installed_at'],
                'unique_together': {('workspace', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_type', models.CharField(choices=[('telegram', 'Telegram'), ('slack', 'Slack'), ('discord', 'Discord'), ('whatsapp', 'WhatsApp'), ('teams', 'Microsoft Teams')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('credentials', models.JSONField(default=dict, help_text='Channel-specific credentials and tokens')),
                ('allowlist', models.JSONField(default=list, help_text='List of allowed users/groups/channels')),
                ('is_active', models.BooleanField(default=True)),
                ('respond_to_groups', models.BooleanField(default=False, help_text='Whether to respond in group chats')),
                ('oauth_state', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
                'ordering': ['-created_at'],
                'unique_together': {('workspace', 'channel_type')},
            },
        ),
    ]
