# Generated by Django 5.2.10 on 2026-02-02 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='agent_description',
            field=models.TextField(blank=True, help_text='Brief description of what this agent does'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='agent_name',
            field=models.CharField(blank=True, default='Assistant', help_text='The name the agent uses to identify itself', max_length=100),
        ),
        migrations.AddField(
            model_name='workspace',
            name='system_prompt',
            field=models.TextField(blank=True, default='You are a helpful AI assistant.', help_text='The system prompt that defines the agent behavior'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='temperature',
            field=models.FloatField(default=0.7, help_text='Controls randomness (0.0 = deterministic, 1.0 = creative)'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='welcome_message',
            field=models.TextField(blank=True, default='Hello! How can I help you today?', help_text='Message sent when a user first interacts'),
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('document', 'Document'), ('text', 'Text Snippet'), ('url', 'Web URL'), ('faq', 'FAQ Entry')], default='text', max_length=20)),
                ('content', models.TextField(blank=True, help_text='Text content or extracted document text')),
                ('file', models.FileField(blank=True, help_text='Uploaded document file', null=True, upload_to='knowledge_base/')),
                ('source_url', models.URLField(blank=True, help_text='Source URL if this is a web resource')),
                ('question', models.TextField(blank=True, help_text='Question (for FAQ type)')),
                ('answer', models.TextField(blank=True, help_text='Answer (for FAQ type)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_base', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Knowledge Base Entry',
                'verbose_name_plural': 'Knowledge Base Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
