# Generated by Django 5.2.10 on 2026-02-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_workspace_agent_description_workspace_agent_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installedskill',
            name='clawhub_installed',
            field=models.BooleanField(default=False, help_text='Whether clawhub install was run in the container'),
        ),
        migrations.AddField(
            model_name='installedskill',
            name='install_error',
            field=models.TextField(blank=True, help_text='Error message if installation failed'),
        ),
        migrations.AddField(
            model_name='installedskill',
            name='install_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('installing', 'Installing'), ('ready', 'Ready'), ('error', 'Error'), ('missing_reqs', 'Missing Requirements')], default='pending', help_text='Current installation status', max_length=20),
        ),
    ]
