# Generated by Django 5.2.10 on 2026-02-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_installedskill_clawhub_installed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='gateway_token',
            field=models.CharField(blank=True, help_text='Token for authenticating with the OpenClaw Gateway WebSocket', max_length=64),
        ),
    ]
