"""
Management command to seed ClawHub skills into the database.
Based on the awesome-openclaw-skills collection.
"""
from django.core.management.base import BaseCommand
from skills.models import Skill


CLAWHUB_SKILLS = [
    # Web & Search
    {
        'name': 'Brave Search',
        'slug': 'brave-search',
        'description': 'Web search and content extraction via Brave Search API. Search the web, get summaries, and extract content from URLs.',
        'short_description': 'Web search via Brave Search API',
        'category': 'productivity',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': True,
        'is_featured': True,
        'required_env': ['BRAVE_API_KEY'],
        'tags': ['search', 'web', 'research'],
    },
    {
        'name': 'Google Search',
        'slug': 'google-search',
        'description': 'Search using Google Custom Search Engine. Get accurate search results from Google.',
        'short_description': 'Search using Google CSE',
        'category': 'productivity',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': True,
        'required_env': ['GOOGLE_API_KEY', 'GOOGLE_CSE_ID'],
        'tags': ['search', 'google', 'research'],
    },
    {
        'name': 'Perplexity',
        'slug': 'perplexity',
        'description': 'Perplexity API for web-grounded search with citations. Get AI-powered answers with real sources.',
        'short_description': 'AI search with citations',
        'category': 'productivity',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': True,
        'required_env': ['PERPLEXITY_API_KEY'],
        'tags': ['search', 'ai', 'research'],
    },
    {
        'name': 'Exa Search',
        'slug': 'exa',
        'description': 'Neural web search and code context via Exa AI API. Find relevant content using semantic search.',
        'short_description': 'Neural semantic web search',
        'category': 'productivity',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': True,
        'required_env': ['EXA_API_KEY'],
        'tags': ['search', 'ai', 'semantic'],
    },
    {
        'name': 'Kagi Search',
        'slug': 'kagi-search',
        'description': 'Web search using Kagi Search API. Ad-free, privacy-focused search results.',
        'short_description': 'Privacy-focused web search',
        'category': 'productivity',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': True,
        'required_env': ['KAGI_API_KEY'],
        'tags': ['search', 'privacy', 'research'],
    },
    # Browser & Automation
    {
        'name': 'Playwright Browser',
        'slug': 'playwright-cli',
        'description': 'Browser automation via Playwright CLI. Automate web interactions, take screenshots, fill forms, and scrape data.',
        'short_description': 'Browser automation with Playwright',
        'category': 'automation',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': True,
        'is_featured': True,
        'tags': ['browser', 'automation', 'scraping'],
    },
    {
        'name': 'Firecrawl',
        'slug': 'firecrawl',
        'description': 'Web scraping and crawling via Firecrawl API. Extract structured data from websites at scale.',
        'short_description': 'Web scraping and crawling',
        'category': 'automation',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': True,
        'required_env': ['FIRECRAWL_API_KEY'],
        'tags': ['scraping', 'crawling', 'data'],
    },
    {
        'name': 'Browser Use',
        'slug': 'browser-use',
        'description': 'Cloud-based browser automation with managed sessions. Control browsers in the cloud for testing and automation.',
        'short_description': 'Cloud browser automation',
        'category': 'automation',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': True,
        'required_env': ['BROWSERBASE_API_KEY'],
        'tags': ['browser', 'cloud', 'automation'],
    },
    {
        'name': 'Computer Use',
        'slug': 'computer-use',
        'description': 'Full desktop automation for headless Linux servers. Control mouse, keyboard, and screen programmatically.',
        'short_description': 'Desktop automation',
        'category': 'automation',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': True,
        'is_featured': True,
        'tags': ['desktop', 'automation', 'linux'],
    },
    {
        'name': '2Captcha Solver',
        'slug': '2captcha',
        'description': 'Solve CAPTCHAs using 2Captcha service. Bypass CAPTCHAs in automated workflows.',
        'short_description': 'CAPTCHA solving service',
        'category': 'automation',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': False,
        'required_env': ['TWOCAPTCHA_API_KEY'],
        'tags': ['captcha', 'automation', 'bypass'],
    },
    # Git & GitHub
    {
        'name': 'GitHub',
        'slug': 'github',
        'description': 'Interact with GitHub using the gh CLI. Create repos, manage issues, pull requests, and more.',
        'short_description': 'GitHub CLI integration',
        'category': 'development',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': True,
        'is_featured': True,
        'required_env': ['GITHUB_TOKEN'],
        'tags': ['github', 'git', 'development'],
    },
    {
        'name': 'GitLab Manager',
        'slug': 'gitlab-manager',
        'description': 'Manage GitLab repositories, merge requests, and issues via API.',
        'short_description': 'GitLab API integration',
        'category': 'development',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': True,
        'required_env': ['GITLAB_TOKEN'],
        'tags': ['gitlab', 'git', 'development'],
    },
    {
        'name': 'Conventional Commits',
        'slug': 'conventional-commits',
        'description': 'Format commits using Conventional Commits specification. Ensure consistent commit messages.',
        'short_description': 'Standardized commit messages',
        'category': 'development',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': True,
        'tags': ['git', 'commits', 'standards'],
    },
    # DevOps & Cloud
    {
        'name': 'Docker Essentials',
        'slug': 'docker-essentials',
        'description': 'Essential Docker commands for container management. Build, run, and manage containers.',
        'short_description': 'Docker container management',
        'category': 'development',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': True,
        'is_featured': True,
        'tags': ['docker', 'containers', 'devops'],
    },
    {
        'name': 'Kubernetes',
        'slug': 'kubernetes',
        'description': 'Comprehensive Kubernetes and OpenShift cluster management. Deploy and manage containerized applications.',
        'short_description': 'Kubernetes cluster management',
        'category': 'development',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': True,
        'tags': ['kubernetes', 'k8s', 'devops'],
    },
    {
        'name': 'AWS Infrastructure',
        'slug': 'aws-infra',
        'description': 'Chat-based AWS infrastructure assistance. Manage EC2, S3, Lambda, and other AWS services.',
        'short_description': 'AWS cloud management',
        'category': 'development',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': True,
        'required_env': ['AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY'],
        'tags': ['aws', 'cloud', 'infrastructure'],
    },
    {
        'name': 'Azure CLI',
        'slug': 'azure-cli',
        'description': 'Comprehensive Azure Cloud Platform management. Deploy and manage Azure resources.',
        'short_description': 'Azure cloud management',
        'category': 'development',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': True,
        'tags': ['azure', 'cloud', 'microsoft'],
    },
    {
        'name': 'Google Cloud',
        'slug': 'gcloud',
        'description': 'Manage Google Cloud Platform resources via gcloud CLI.',
        'short_description': 'GCP cloud management',
        'category': 'development',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': True,
        'tags': ['gcp', 'cloud', 'google'],
    },
    {
        'name': 'Ansible',
        'slug': 'ansible-skill',
        'description': 'Infrastructure automation with Ansible. Automate server configuration and deployment.',
        'short_description': 'Infrastructure automation',
        'category': 'development',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': True,
        'tags': ['ansible', 'automation', 'infrastructure'],
    },
    {
        'name': 'Coolify',
        'slug': 'coolify',
        'description': 'Manage Coolify deployments, applications, and databases. Self-hosted PaaS alternative.',
        'short_description': 'Self-hosted PaaS management',
        'category': 'development',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': False,
        'required_env': ['COOLIFY_API_KEY'],
        'tags': ['coolify', 'deployment', 'paas'],
    },
    {
        'name': 'Fly.io',
        'slug': 'flyio-cli',
        'description': 'Fly.io deploy, logs, SSH, secrets, and scaling. Deploy apps globally on Fly.io.',
        'short_description': 'Fly.io deployment',
        'category': 'development',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': False,
        'tags': ['flyio', 'deployment', 'cloud'],
    },
    # Coding & Development
    {
        'name': 'Next.js Expert',
        'slug': 'nextjs-expert',
        'description': 'Building Next.js 14/15 applications with App Router. Best practices for React Server Components.',
        'short_description': 'Next.js development expert',
        'category': 'development',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': True,
        'is_featured': True,
        'tags': ['nextjs', 'react', 'frontend'],
    },
    {
        'name': 'Senior Fullstack',
        'slug': 'senior-fullstack',
        'description': 'Fullstack development with project scaffolding for multiple stacks. Build complete applications.',
        'short_description': 'Fullstack development',
        'category': 'development',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': True,
        'tags': ['fullstack', 'backend', 'frontend'],
    },
    {
        'name': 'TDD Guide',
        'slug': 'tdd-guide',
        'description': 'Test-driven development workflow with test generation. Write tests before code.',
        'short_description': 'Test-driven development',
        'category': 'development',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': True,
        'tags': ['testing', 'tdd', 'quality'],
    },
    {
        'name': 'Debug Pro',
        'slug': 'debug-pro',
        'description': 'Systematic debugging methodology and language-specific commands. Debug code efficiently.',
        'short_description': 'Professional debugging',
        'category': 'development',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': True,
        'tags': ['debugging', 'troubleshooting', 'development'],
    },
    {
        'name': 'MCP Builder',
        'slug': 'mcp-builder',
        'description': 'Guide for creating high-quality MCP (Model Context Protocol) servers.',
        'short_description': 'Build MCP servers',
        'category': 'development',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': True,
        'tags': ['mcp', 'ai', 'servers'],
    },
    # Communication
    {
        'name': 'Discord',
        'slug': 'discord',
        'description': 'Control Discord via the discord tool for messaging and reactions. Send messages, manage servers.',
        'short_description': 'Discord bot integration',
        'category': 'communication',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': True,
        'required_env': ['DISCORD_BOT_TOKEN'],
        'tags': ['discord', 'messaging', 'chat'],
    },
    {
        'name': 'Slack',
        'slug': 'slack',
        'description': 'Slack workspace integration. Send messages, manage channels, and automate workflows.',
        'short_description': 'Slack workspace integration',
        'category': 'communication',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': True,
        'required_env': ['SLACK_BOT_TOKEN'],
        'tags': ['slack', 'messaging', 'workspace'],
    },
    {
        'name': 'Telegram Bot',
        'slug': 'telegram',
        'description': 'Telegram bot integration for messaging and automation.',
        'short_description': 'Telegram bot integration',
        'category': 'communication',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': True,
        'required_env': ['TELEGRAM_BOT_TOKEN'],
        'tags': ['telegram', 'messaging', 'bot'],
    },
    {
        'name': 'Email (Zoho)',
        'slug': 'zoho-email',
        'description': 'Zoho Mail integration with OAuth2, REST API, HTML emails, and attachments.',
        'short_description': 'Zoho email integration',
        'category': 'communication',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': False,
        'required_env': ['ZOHO_CLIENT_ID', 'ZOHO_CLIENT_SECRET'],
        'tags': ['email', 'zoho', 'communication'],
    },
    {
        'name': 'React Email',
        'slug': 'react-email-skills',
        'description': 'Create responsive HTML emails using React components.',
        'short_description': 'React email templates',
        'category': 'communication',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': False,
        'tags': ['email', 'react', 'templates'],
    },
    # AI & Image Generation
    {
        'name': 'Fal.ai',
        'slug': 'fal-ai',
        'description': 'Generate images, videos, and audio via Fal.ai API. Access multiple AI models.',
        'short_description': 'AI media generation',
        'category': 'ai',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': True,
        'is_featured': True,
        'required_env': ['FAL_API_KEY'],
        'tags': ['ai', 'images', 'generation'],
    },
    {
        'name': 'ComfyUI',
        'slug': 'comfy-ai',
        'description': 'Integrates with local ComfyUI instance for text-to-image generation.',
        'short_description': 'Local image generation',
        'category': 'ai',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': False,
        'tags': ['comfyui', 'images', 'local'],
    },
    {
        'name': 'AI Video Gen',
        'slug': 'ai-video-gen',
        'description': 'End-to-end AI video creation from text prompts.',
        'short_description': 'AI video generation',
        'category': 'ai',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': False,
        'tags': ['ai', 'video', 'generation'],
    },
    {
        'name': 'Chart Image',
        'slug': 'chart-image',
        'description': 'Generate publication-quality chart images. Create graphs and visualizations.',
        'short_description': 'Chart and graph generation',
        'category': 'productivity',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': False,
        'tags': ['charts', 'visualization', 'images'],
    },
    {
        'name': 'Remotion Video',
        'slug': 'remotion-video-toolkit',
        'description': 'Complete toolkit for programmatic video creation with Remotion + React.',
        'short_description': 'Programmatic video creation',
        'category': 'ai',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': False,
        'tags': ['video', 'remotion', 'react'],
    },
    {
        'name': 'Gamma Presentations',
        'slug': 'gamma',
        'description': 'Generate AI presentations and documents using Gamma.app API.',
        'short_description': 'AI presentation generator',
        'category': 'productivity',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': False,
        'required_env': ['GAMMA_API_KEY'],
        'tags': ['presentations', 'ai', 'documents'],
    },
    # Apple/macOS
    {
        'name': 'Apple Contacts',
        'slug': 'apple-contacts',
        'description': 'Look up contacts from macOS Contacts.app.',
        'short_description': 'macOS contacts integration',
        'category': 'productivity',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': False,
        'tags': ['apple', 'macos', 'contacts'],
    },
    {
        'name': 'Apple Music',
        'slug': 'apple-music',
        'description': 'Search Apple Music, manage playlists, and control playback.',
        'short_description': 'Apple Music control',
        'category': 'productivity',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': False,
        'tags': ['apple', 'music', 'macos'],
    },
    {
        'name': 'Homebrew',
        'slug': 'homebrew',
        'description': 'Homebrew package manager for macOS. Install and manage packages.',
        'short_description': 'macOS package manager',
        'category': 'development',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': True,
        'tags': ['homebrew', 'macos', 'packages'],
    },
    {
        'name': 'iCloud Find My',
        'slug': 'icloud-findmy',
        'description': 'Query Find My locations and battery status for Apple devices.',
        'short_description': 'iCloud Find My integration',
        'category': 'productivity',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': False,
        'tags': ['apple', 'icloud', 'location'],
    },
    # Data & Databases
    {
        'name': 'PostgreSQL',
        'slug': 'postgresql',
        'description': 'PostgreSQL database management. Query, manage schemas, and optimize databases.',
        'short_description': 'PostgreSQL database management',
        'category': 'development',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': True,
        'tags': ['postgresql', 'database', 'sql'],
    },
    {
        'name': 'MongoDB',
        'slug': 'mongodb',
        'description': 'MongoDB database operations. Query and manage NoSQL databases.',
        'short_description': 'MongoDB management',
        'category': 'development',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': True,
        'tags': ['mongodb', 'database', 'nosql'],
    },
    {
        'name': 'Redis',
        'slug': 'redis-skill',
        'description': 'Redis cache and database operations. Manage keys, lists, and pub/sub.',
        'short_description': 'Redis cache management',
        'category': 'development',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': True,
        'tags': ['redis', 'cache', 'database'],
    },
    # Productivity
    {
        'name': 'Notion',
        'slug': 'notion',
        'description': 'Notion workspace integration. Create pages, manage databases, and organize content.',
        'short_description': 'Notion workspace integration',
        'category': 'productivity',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': True,
        'required_env': ['NOTION_API_KEY'],
        'tags': ['notion', 'productivity', 'notes'],
    },
    {
        'name': 'Linear',
        'slug': 'linear',
        'description': 'Linear issue tracking integration. Create and manage issues, projects, and cycles.',
        'short_description': 'Linear issue tracking',
        'category': 'productivity',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': True,
        'required_env': ['LINEAR_API_KEY'],
        'tags': ['linear', 'issues', 'project-management'],
    },
    {
        'name': 'Todoist',
        'slug': 'todoist',
        'description': 'Todoist task management. Create tasks, manage projects, and track productivity.',
        'short_description': 'Todoist task management',
        'category': 'productivity',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': False,
        'required_env': ['TODOIST_API_KEY'],
        'tags': ['todoist', 'tasks', 'productivity'],
    },
    {
        'name': 'Airtable',
        'slug': 'airtable',
        'description': 'Airtable database integration. Query and manage Airtable bases.',
        'short_description': 'Airtable integration',
        'category': 'productivity',
        'author': 'ClawHub',
        'repository_url': 'https://github.com/openclaw/skills',
        'is_official': False,
        'required_env': ['AIRTABLE_API_KEY'],
        'tags': ['airtable', 'database', 'productivity'],
    },
]


class Command(BaseCommand):
    help = 'Seed ClawHub skills into the database'

    def add_arguments(self, parser):
        parser.add_argument(
            '--clear',
            action='store_true',
            help='Clear existing skills before seeding',
        )

    def handle(self, *args, **options):
        if options['clear']:
            count = Skill.objects.count()
            Skill.objects.all().delete()
            self.stdout.write(self.style.WARNING(f'Deleted {count} existing skills'))

        created_count = 0
        updated_count = 0

        for skill_data in CLAWHUB_SKILLS:
            skill, created = Skill.objects.update_or_create(
                slug=skill_data['slug'],
                defaults={
                    'name': skill_data['name'],
                    'description': skill_data['description'],
                    'short_description': skill_data.get('short_description', ''),
                    'category': skill_data.get('category', 'other'),
                    'author': skill_data.get('author', 'Community'),
                    'repository_url': skill_data.get('repository_url', ''),
                    'is_official': skill_data.get('is_official', False),
                    'is_featured': skill_data.get('is_featured', False),
                    'required_env': skill_data.get('required_env', []),
                    'tags': skill_data.get('tags', []),
                    'is_active': True,
                }
            )
            if created:
                created_count += 1
            else:
                updated_count += 1

        self.stdout.write(
            self.style.SUCCESS(
                f'Successfully seeded {created_count} new skills, updated {updated_count} existing skills'
            )
        )
        self.stdout.write(
            self.style.SUCCESS(f'Total skills in database: {Skill.objects.count()}')
        )
