# Generated by Django 5.2.11 on 2026-02-05 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0004_add_gateway_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('company', models.CharField(max_length=300)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('url', models.URLField(max_length=2000)),
                ('description', models.TextField(blank=True)),
                ('salary_info', models.CharField(blank=True, max_length=200)),
                ('job_type', models.CharField(blank=True, max_length=50)),
                ('source_board', models.CharField(max_length=50)),
                ('external_id', models.CharField(blank=True, max_length=200)),
                ('match_score', models.IntegerField(default=0)),
                ('score_breakdown', models.JSONField(default=dict)),
                ('matched_keywords', models.JSONField(default=list)),
                ('url_hash', models.CharField(db_index=True, max_length=64)),
                ('dismissed', models.BooleanField(default=False)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-match_score', '-discovered_at'],
                'unique_together': {('user', 'url_hash')},
            },
        ),
        migrations.CreateModel(
            name='JobPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.JSONField(default=list, help_text='Search keywords: ["Django Developer", "Full Stack", "React"]')),
                ('excluded_keywords', models.JSONField(default=list, help_text='Exclude jobs with: ["C++", "Director", ".NET"]')),
                ('location', models.CharField(default='Toronto', max_length=200)),
                ('remote_ok', models.BooleanField(default=True)),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('enabled_boards', models.JSONField(default=list, help_text='["linkedin", "indeed", "glassdoor"]')),
                ('auto_apply_enabled', models.BooleanField(default=False)),
                ('auto_apply_min_score', models.IntegerField(default=70, help_text='Only auto-apply to jobs scoring >= this')),
                ('max_daily_applications', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_preferences', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, help_text='Workspace whose OpenClaw container handles browser automation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='resumes/')),
                ('file_type', models.CharField(default='pdf', max_length=10)),
                ('extracted_text', models.TextField(blank=True, help_text='Raw text extracted from PDF/DOCX')),
                ('parsed_data', models.JSONField(default=dict, help_text='Claude-parsed: {name, email, phone, location, summary, skills[], experience[], education[]}')),
                ('is_primary', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyApplicationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('jobs_discovered', models.IntegerField(default=0)),
                ('applications_sent', models.IntegerField(default=0)),
                ('applications_failed', models.IntegerField(default=0)),
                ('high_score_jobs', models.IntegerField(default=0)),
                ('summary_text', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('generating_cover', 'Generating Cover Letter'), ('applying', 'Applying'), ('applied', 'Applied'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('interview', 'Interview'), ('offer', 'Offer'), ('withdrawn', 'Withdrawn')], default='queued', max_length=30)),
                ('cover_letter', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_via', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('automation_log', models.JSONField(default=list, help_text='Step-by-step browser actions: [{step, action, ref, result}]')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobapply.joblisting')),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobapply.resume')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'listing')},
            },
        ),
    ]
