# Generated by Django 5.2.10 on 2026-02-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skill_api_keys',
            field=models.JSONField(blank=True, default=dict, help_text='Additional API keys required by skills (e.g., BRAVE_API_KEY for web search)'),
        ),
    ]
